# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
units: bin/units.tsv
# path or URL to contrast sheet (TSV format, columns: sample, condition, ...)
contrasts: bin/contrasts.tsv

ref:
  # path/to/reference/gDNA.fasta
  sequence:
    arikara:      references/HanXRQr2.0-SUNRISE-2.1_arikara_consensus.fa
    nebraska:     references/HanXRQr2.0-SUNRISE-2.1_nebraska_consensus.fa
  fai:            # .fai here
  # path/to/STAR/index/directory
  index:
    arikara:      references/star_indexes/arikara
    nebraska:     references/star_indexes/nebraska
  # path/to/gtf/file/with/transcripts.gtf
  annotation:
    arikara:      references/HanXRQr2.0-SUNRISE-2.1_arikara_consensus.gtf
    nebraska:     references/HanXRQr2.0-SUNRISE-2.1_nebraska_consensus.gtf
  # known variants (Broad resource downloaded here: https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/hg38/v0/)
  # e.g. known_snps:     /secondary/projects/bbc/research/broad_resource_bundle_hg38/Homo_sapiens_assembly38.dbsnp138.vcf
  # e.g. known_indels:   /secondary/projects/bbc/research/broad_resource_bundle_hg38/Homo_sapiens_assembly38.known_indels.vcf.gz
  # e.g. snpeff_db_id:   "GRCh38.86"
# are the sequencing reads paired-end ('PE') or single-end ('SE')
PE_or_SE:         PE

# what is the strandedness of the kit used for library prep?
# options: "forward", "reverse", "unstranded" (usually reverse)
strandedness:     reverse

### EdgeR Variables ###

# used for annotation. see src/annotation.tsv for common_name options. e.g.:  "mouse", "human", "fly"
common_name:      sunflower
# differential expression cutoff values
logfc.filter:     1
fdr.filter:       0.05

# Boolean for whether to call variants. Requires 'variant_calling_units.tsv'
# snpRelate html report only generated if conda is callable. Otherwise, the snpRelate rule is not run.
call_variants:  FALSE
